
server:
  port: 8082
spring:
  profiles:
    active:
    - stage 
  application:
    name: USER_SERVICE
    
---   
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/shop24x7_stage
    username: root
    password: samuel545
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: prod
 

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/shop24x7_stage
    username: root
    password: samuel545
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: qa

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/shop24x7_stage
    username: root
    password: samuel545
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: preqa
---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/shop24x7_stage
    username: root
    password: samuel545
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'false'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    activate:
      on-profile: stage
  
    
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka   

